### ISSUE TITLE
[Feat] MessageView - Person 구현

### ISSUE THREAD

**Issue by ejalice** [ejalice/SwiftUI-Damda#10]
**Issue : Feature**
| DateFixed | Person |
|:---:|:---:|
|<img width="130" alt="스크린샷 2022-11-25 오후 10 35 42" src="https://user-images.githubusercontent.com/83203198/203996942-8ad1fc61-1ca9-424b-92c4-1b3872e6ef95.png">|<img width="400" alt="스크린샷 2022-11-25 오후 10 35 33" src="https://user-images.githubusercontent.com/83203198/203996959-607b8d9c-1893-4f53-b618-c6e433f73770.png">|

**Description**
- User가 선택한 날짜 보여주는 UI 구현
- Person 입력 UI 구현

**Todo**
- [x] Date Data 저장
- [x] 키보드 구현
    - [x] Person 질문 후 키보드 자동 띄우기
    - [x] 키보드 multiline
    - [x] 키보드 하단에 고정
    - [x] 버튼 생성 및 활성화
- [x] 입력받은 Person Data 저장
- [x] Message 말풍선 UI 및 delay 구현
    - [x] User 입장 - Date 답변
    - [x] Damda입장 - Person 관련 질문
    - [x] User 입장 - Person 답변 

**Reference(Optional)**
사용자의 날짜 선택 확정에 대해 의논이 필요할 것 같습니다.
