### ISSUE TITLE
[Feat] MessageView-Message 구현

### ISSUE THREAD

**Issue by ejalice** [ejalice/SwiftUI-Damda#6]
**Issue : Feature**
|Figma|
|:---:|
|<img width="300" alt="스크린샷 2022-11-23 오전 3 56 42" src="https://user-images.githubusercontent.com/83203198/203558936-cd7a066b-7fcd-4e79-bace-a3b0f07dc2ca.png">|

**Description**
- UI구현

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] Message Model 생성
- [x] Message 말풍성 생성
- [x] Message 자동으로 띄워주기
