### ISSUE TITLE
[Feat] MessageView-Date 구현

### ISSUE THREAD

**Issue by ejalice** [ejalice/SwiftUI-Damda#7]
**Issue : Feature**
|Figma|
|:---:|
|<img width="315" alt="스크린샷 2022-11-23 오후 11 54 11" src="https://user-images.githubusercontent.com/83203198/203578141-bd8c9b73-f513-493e-b55d-9040e2951053.png">|

**Description**
- UI 작업

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] Button 생성
- [x] Button 선택에 따른 UI 작업 -> Calender O or X
- [x] Button 자동으로 띄워주기
- [x] Button 선택에 따른 ScrollView 크기 변환 작업
